// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEjwi5AcEGg8ewOaZFi3B1y4pUEdLpYFE',
    appId: '1:581913523036:web:53591bf7619357e66c4799',
    messagingSenderId: '581913523036',
    projectId: 'pollution-project-4f27e',
    authDomain: 'pollution-project-4f27e.firebaseapp.com',
    storageBucket: 'pollution-project-4f27e.appspot.com',
    measurementId: 'G-3GECNC252W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKjxD1AnmjHnXiZgDzTPluqHlf8og_QsU',
    appId: '1:581913523036:android:e9083e3880c992216c4799',
    messagingSenderId: '581913523036',
    projectId: 'pollution-project-4f27e',
    storageBucket: 'pollution-project-4f27e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzD_DuGEOKSolsHIzVqxaltJearAGWLsE',
    appId: '1:581913523036:ios:20ba4f516495aba86c4799',
    messagingSenderId: '581913523036',
    projectId: 'pollution-project-4f27e',
    storageBucket: 'pollution-project-4f27e.appspot.com',
    iosBundleId: 'com.example.pollutionProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzD_DuGEOKSolsHIzVqxaltJearAGWLsE',
    appId: '1:581913523036:ios:3444564205d828a86c4799',
    messagingSenderId: '581913523036',
    projectId: 'pollution-project-4f27e',
    storageBucket: 'pollution-project-4f27e.appspot.com',
    iosBundleId: 'com.example.pollutionProject.RunnerTests',
  );
}
